### ISSUE TITLE
Feature request : support __tracebackhide__

### ISSUE THREAD

**Issue by LunarLanding** [ionelmc/python-tblib#67] opened 2022-08-04 16:27 UTC
Frameworks / decorators add to tracebacks a lot, and ipython / pytest have a mechanism to hide frames which define the local variable `__tracebackhide__` :  https://github.com/Carreau/ipython/blob/7a937c90ad2238647694c3bdff2e545ffc5932c5/IPython/core/debugger.py#L291

This feature could be supported by copying the value of `__tracebackhide__` from the original frame, if existing, into f_locals.
PS: pytest mentions this in this [page](https://doc.pytest.org/en/latest/example/simple.html#writing-well-integrated-assertion-helpers).

**Comment by ionelmc** [comment] 2023-06-22 08:25
Dupe of #41, lets discuss there.

**Closed by ionelmc** 2023-06-22 08:25 UTC
